package me.tagavari.airmessage.compose.ui.theme

import androidx.compose.ui.graphics.Color

object AMColor {
	val md_theme_light_primary = Color(0xFF005AC2)
	val md_theme_light_onPrimary = Color(0xFFFFFFFF)
	val md_theme_light_primaryContainer = Color(0xFFD8E2FF)
	val md_theme_light_onPrimaryContainer = Color(0xFF001A42)
	val md_theme_light_secondary = Color(0xFF0061A6)
	val md_theme_light_onSecondary = Color(0xFFFFFFFF)
	val md_theme_light_secondaryContainer = Color(0xFFD2E4FF)
	val md_theme_light_onSecondaryContainer = Color(0xFF001C37)
	val md_theme_light_tertiary = Color(0xFF006D35)
	val md_theme_light_onTertiary = Color(0xFFFFFFFF)
	val md_theme_light_tertiaryContainer = Color(0xFF62FF96)
	val md_theme_light_onTertiaryContainer = Color(0xFF00210B)
	val md_theme_light_error = Color(0xFFBA1A1A)
	val md_theme_light_errorContainer = Color(0xFFFFDAD6)
	val md_theme_light_onError = Color(0xFFFFFFFF)
	val md_theme_light_onErrorContainer = Color(0xFF410002)
	val md_theme_light_background = Color(0xFFFEFBFF)
	val md_theme_light_onBackground = Color(0xFF1B1B1F)
	val md_theme_light_surface = Color(0xFFFEFBFF)
	val md_theme_light_onSurface = Color(0xFF1B1B1F)
	val md_theme_light_surfaceVariant = Color(0xFFE1E2EC)
	val md_theme_light_onSurfaceVariant = Color(0xFF44474F)
	val md_theme_light_outline = Color(0xFF75777F)
	val md_theme_light_inverseOnSurface = Color(0xFFF2F0F4)
	val md_theme_light_inverseSurface = Color(0xFF303033)
	val md_theme_light_inversePrimary = Color(0xFFADC6FF)
	val md_theme_light_shadow = Color(0xFF000000)
	val md_theme_light_surfaceTint = Color(0xFF005AC2)
	
	val md_theme_dark_primary = Color(0xFFADC6FF)
	val md_theme_dark_onPrimary = Color(0xFF002E6A)
	val md_theme_dark_primaryContainer = Color(0xFF004495)
	val md_theme_dark_onPrimaryContainer = Color(0xFFD8E2FF)
	val md_theme_dark_secondary = Color(0xFFA0C9FF)
	val md_theme_dark_onSecondary = Color(0xFF00325A)
	val md_theme_dark_secondaryContainer = Color(0xFF00497F)
	val md_theme_dark_onSecondaryContainer = Color(0xFFD2E4FF)
	val md_theme_dark_tertiary = Color(0xFF00E475)
	val md_theme_dark_onTertiary = Color(0xFF003918)
	val md_theme_dark_tertiaryContainer = Color(0xFF005226)
	val md_theme_dark_onTertiaryContainer = Color(0xFF62FF96)
	val md_theme_dark_error = Color(0xFFFFB4AB)
	val md_theme_dark_errorContainer = Color(0xFF93000A)
	val md_theme_dark_onError = Color(0xFF690005)
	val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
	val md_theme_dark_background = Color(0xFF1B1B1F)
	val md_theme_dark_onBackground = Color(0xFFE3E2E6)
	val md_theme_dark_surface = Color(0xFF1B1B1F)
	val md_theme_dark_onSurface = Color(0xFFE3E2E6)
	val md_theme_dark_surfaceVariant = Color(0xFF44474F)
	val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)
	val md_theme_dark_outline = Color(0xFF8E9099)
	val md_theme_dark_inverseOnSurface = Color(0xFF1B1B1F)
	val md_theme_dark_inverseSurface = Color(0xFFE3E2E6)
	val md_theme_dark_inversePrimary = Color(0xFF005AC2)
	val md_theme_dark_shadow = Color(0xFF000000)
	val md_theme_dark_surfaceTint = Color(0xFFADC6FF)
	
	val seed = Color(0xFF448AFF)
}